spring:
  datasource:
    url: "jdbc:postgresql://grakovne.org:5432/mds"
    username: mds
    password: vkVRzABjS5dHt5vEPavRYSxGDB2dk36E
    driver-class-name: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
    port: 5050
