spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mds"
    username: mds
    password: vkVRzABjS5dHt5vEPavRYSxGDB2dk36E
    driver-class-name: org.postgresql.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  http:
    multipart:
      max-file-size: -1
      max-request-size: -1
  config:
      fileUploadDirectory: C:\Users\GrakovNe\Desktop\mds
server:
    port: 5050
